config/routes.rb
Authz::Engine.routes.draw do

  root 'home#index'
  resources :controller_actions
  resources :pending_controller_actions, only: [:index]
  resources :stale_controller_actions, only: [:index]
  resources :business_processes
  resources :roles do
    resources :scoping_rules, only: [:new, :create, :edit, :update]
  end

  namespace :bulk do
    post 'controller_actions/create'
    delete 'controller_actions/destroy'
  end

  namespace :validations do
    resources :controller_names, only: [:new]
    resources :action_names, only: [:new]
    resources :business_process_names, only: [:new, :edit]
    resources :role_names, only: [:new, :edit]
  end

  Authz.rolables.each do |rolable|
    resources rolable.authorizable_association_name, only: [:index, :show, :edit, :update], controller: :rolables
  end

end

app/models/authz/application_record.rb
module Authz
  # Superclass for all internal models
  # @api private
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true

    # Forces the use of Rails 5.1 and below for #cache_key.
    # This is limited to the gem's inner workings so the
    # host app is not affected.
    # #cache_key will include timestamp.
    self.cache_versioning = false if Authz.cache.active_record_has_cache_versioning_available?

  end
end

app/models/authz/business_process.rb
module Authz
  # Represents a real-life process of the business.
  # For example, a newspaper might have "publish reports" and "write reports" processes.
  class BusinessProcess < self::ApplicationRecord
    # Validations
    # ==========================================================================
    validates :code, presence: true, uniqueness: true,
                     format: { with: /\A[a-z][a-z0-9]*(_[a-z0-9]+)*\z/,
                               message: 'only snake_case allowed' }
    validates :name, presence: true, uniqueness: true
    validates :description, presence: true

    # Callbacks
    # ==========================================================================
    before_validation :extract_code_from_name, on: [:create]
    after_touch :touch_roles
    after_update :touch_roles

    # Associations
    # ==========================================================================
    has_many :business_process_has_controller_actions,
             class_name: 'Authz::BusinessProcessHasControllerAction',
             foreign_key: 'authz_business_process_id',
             inverse_of: :business_process,
             dependent: :destroy
    has_many :controller_actions,
             through: :business_process_has_controller_actions,
             dependent: :destroy
    has_many :role_has_business_processes,
             class_name: 'Authz::RoleHasBusinessProcess',
             foreign_key: 'authz_business_process_id',
             inverse_of: :business_process,
             dependent: :destroy
    has_many :roles,
             through: :role_has_business_processes,
             dependent: :destroy
    has_many :role_grants, through: :roles

    private

    def extract_code_from_name
      self.code = name.parameterize(separator: '_') if name.present?
    end

    def touch_roles
      roles.update_all(updated_at: Time.now)
    end

  end
end

app/controllers/authz/application_controller.rb
module Authz
  # Inherits from the host app's ApplicationController so that all of it's methods
  # are available for the engine.
  #
  # All engine's controllers inherit from this class.
  # @api private
  class ApplicationController < ::ApplicationController
    include Authz::Controllers::AuthorizationManager

    protect_from_forgery with: :exception
    before_action :authenticate_authz_user
    before_action { authorize skip_scoping: true }
    around_action :verify_authorized

    private
    # Calls the authentication method configured by the main application
    def authenticate_authz_user
      send(Authz.force_authentication_method)
    end

  end
end

app/controllers/authz/bulk/controller_actions_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class Bulk::ControllerActionsController < ApplicationController

    def create
      pending_actions = Authz::ControllerAction.create_all_pending!
      flash[:success] = "#{pending_actions.size} actions successfully created!"
      redirect_to root_path
    end

    def destroy
      ActiveRecord::Base.transaction do
        @stale_actions = ::Authz::ControllerAction.stale
        @stale_actions.each do |controller_action_hash|
          ::Authz::ControllerAction.find_by(
            controller: controller_action_hash[:controller],
            action: controller_action_hash[:action],
          ).destroy!
        end
      end
      flash[:success] = "#{@stale_actions.count} actions successfully destroyed!"
      redirect_to root_path
    end

  end
end

app/controllers/authz/business_processes_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class BusinessProcessesController < ApplicationController

    def index
      @business_processes = BusinessProcess.all.order(created_at: :desc).page(params[:business_processes_page])
    end

    def show
      @business_process = BusinessProcess.find(params[:id])
      @associated_controller_actions = @business_process.controller_actions.distinct.page(params[:controller_actions_page]).per(10)
      @associated_roles = @business_process.roles.distinct.page(params[:roles_page]).per(10)
    end

    def new
      @business_process = BusinessProcess.new
    end

    def create
      @business_process = BusinessProcess.new(business_process_params)
      if @business_process.save
        redirect_to business_process_path(@business_process)
        flash[:success] = "#{@business_process.name} created successfully"
      else
        flash.now[:error] = "There was an issue creating this business process"
        render 'new'
      end
    end

    def edit
      @business_process = BusinessProcess.find(params[:id])
    end

    def update
      @business_process = BusinessProcess.find(params[:id])
      if @business_process.update(business_process_params)
        flash[:success] = "#{@business_process.name} updated successfully"
        redirect_to business_process_path(@business_process)
      else
        flash.now[:error] = "There was an issue updating this business process"
        render 'edit'
      end
    end

    def destroy
      @business_process = BusinessProcess.find(params[:id])
      if @business_process.destroy
        flash[:success] = "#{@business_process.name} destroyed successfully"
        redirect_to business_processes_path
      else
        flash.now[:error] = "There was an issue destroying #{@business_process.name}"
        render 'show'
      end
    end

    private

    def business_process_params
      params.require(:business_process)
            .permit(
              :name,
              :description,
              controller_action_ids: [],
              role_ids: []
            )
    end
  end
end

app/controllers/authz/controller_actions_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class ControllerActionsController < ApplicationController
    def index
      @controller_actions = ControllerAction.all.order(created_at: :desc).page(params[:controller_actions_page])
    end

    def show
      @controller_action = ControllerAction.find(params[:id])
      @associated_business_processes = @controller_action.business_processes.distinct.page(params[:business_processes_page]).per(10)
      @associated_roles = @controller_action.roles.distinct.page(params[:roles_page]).per(10)
    end

    def new
      @controller_action = ControllerAction.new
    end

    def create
      @controller_action = ControllerAction.new(controller_action_create_params)
      if @controller_action.save
        flash[:success] = "#{@controller_action.to_s} created successfully"
        redirect_to controller_action_path(@controller_action)
      else
        flash.now[:error] = "There was an issue creating this controller action"
        render 'new'
      end
    end

    def edit
      @controller_action = ControllerAction.find(params[:id])
    end

    def update
      @controller_action = ControllerAction.find(params[:id])
      if @controller_action.update(controller_action_update_params)
        flash[:success] = "#{@controller_action.to_s} updated successfully"
        redirect_to controller_action_path(@controller_action)
      else
        flash.now[:error] = "There was an issue updating #{@controller_action.to_s}"
        render 'edit'
      end
    end

    def destroy
      @controller_action = ControllerAction.find(params[:id])
      if @controller_action.destroy
        flash[:success] = "#{@controller_action.to_s} destroyed successfully"
        redirect_to controller_actions_path
      else
        flash.now[:error] = "There was an issue destroying #{@controller_action.to_s}"
        render 'show'
      end
    end

    private

    def controller_action_create_params
      params.require(:controller_action)
            .permit(
              :controller,
              :action,
              business_process_ids: []
            )
    end

    def controller_action_update_params
      params.require(:controller_action)
            .permit(
              :controller,
              :action,
              business_process_ids: []
            )
    end
  end
end

app/controllers/authz/home_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class HomeController < ApplicationController
    def index
      @pending_controller_actions = ControllerAction.pending
      @stale_controller_actions = ControllerAction.stale
      @invalid_scoping_rules = ScopingRule.where.not(scopable: Authz::Scopables::Base.get_scopables_names).pluck(:scopable).uniq
    end
  end
end

app/controllers/authz/pending_controller_actions_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class PendingControllerActionsController < ApplicationController
    def index
      @pending_controller_actions = ControllerAction.pending
                                                    .sort_by { |ca| ca[:controller] }
    end
  end
end

app/controllers/authz/rolables_controller.rb
require_dependency "authz/application_controller"

module Authz
  # Handles the controller actions related to the rolables
  # @api private
  class RolablesController < ApplicationController

    def index
      @rolables = rolable.all.page(params[:page])
    end

    def show
      @rolable = rolable.find(params[:id])
      @associated_roles = @rolable.roles.page(1)
      @associated_business_processes = @rolable.business_processes.page(params[:business_processes_page])
      @associated_controller_actions = @rolable.controller_actions.page(params[:controller_actions_page])
    end

    def edit
      @rolable = rolable.find(params[:id])
    end

    def update
      @rolable = rolable.find(params[:id])
      if @rolable.update(rolable_params)
        flash[:success] = "#{@rolable.authz_label} updated successfully"
        redirect_to send("#{@rolable.model_name.singular}_path", @rolable)
      else
        flash.now[:error] = "There was an issue updating #{@rolable.authz_label}"
        render 'edit'
      end
    end

    private

    def rolable
      ::Authz.rolables.each do |klass|
        klass_name = klass.authorizable_association_name
        regex = /\A\/#{klass_name}(\/|\z)/
        next unless regex.match request.path_info
        return klass
      end
    end

    def rolable_params
      params.require(rolable.model_name.singular)
        .permit(role_ids: [])
    end


  end
end

app/controllers/authz/roles_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class RolesController < ApplicationController

    def index
      @roles = Role.all.page(params[:roles_page])
    end

    def show
      @role = Role.find(params[:id])
      @associated_controller_actions = @role.controller_actions.distinct.page(params[:controller_actions_page]).per(10)
      @associated_business_processes = @role.business_processes.distinct.page(params[:business_processes_page]).per(10)
      @scoping_rules = {}
      ::Authz::Scopables::Base.get_scopables_modules.each do |scoping_module|
        @scoping_rules[scoping_module.to_s] = ScopingRule.find_by(scopable: scoping_module.to_s,
                                                                  role: @role)
      end
    end

    def new
      @role = Role.new
    end

    def create
      @role = Role.new(role_params)
      if @role.save
        flash[:success] = "#{@role.name} created successfully"
        redirect_to role_path(@role)
      else
        flash.now[:error] = "There was an issue creating this role"
        render 'new'
      end
    end

    def edit
      @role = Role.find(params[:id])
    end

    def update
      @role = Role.find(params[:id])
      if @role.update(role_params)
        flash[:success] = "#{@role.name} updated successfully"
        redirect_to role_path(@role)
      else
        flash.now[:error] = "There was an issue updating this role"
        render 'edit'
      end
    end

    def destroy
      @role = Role.find(params[:id])
      if @role.destroy
        flash[:success] = "#{@role.name} destroyed successfully"
        redirect_to roles_path
      else
        flash.now[:error] = "There was an issue destroying #{@role.name}"
        render 'show'
      end
    end

    private

    def role_params
      permitted_arguments = [:name, :description, business_process_ids: []]
      ::Authz.rolables.each do |rolable|
        permitted_arguments << { "#{rolable.model_name.singular}_ids"=> [] }
      end
      params.require(:role)
            .permit(permitted_arguments)
    end
  end
end

app/controllers/authz/scoping_rules_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class ScopingRulesController < ApplicationController
    def new
      @role = Role.find(params[:role_id])
      @scopable = params[:scopable]
      @scoping_rule = ScopingRule.new(scopable: @scopable)
      @available_keywords = @scopable.constantize.available_keywords
    end

    def create
      @role = Role.find(params[:role_id])
      @scopable = scoping_rule_params[:scopable]
      @scoping_rule = ScopingRule.new(scoping_rule_params.merge(authz_role_id: @role.id))
      @available_keywords = @scopable.constantize.available_keywords
      if @scoping_rule.save
        flash[:success] = "Configured #{@scoping_rule.scopable}:#{@scoping_rule.keyword} for #{@role.name}"
        redirect_to role_path(@role)
      else
        flash.now[:error] = 'There was an issue adding this scoping rule'
        render 'new'
      end
    end

    def edit
      @role = Role.find(params[:role_id])
      @scoping_rule = ScopingRule.find(params[:id])
      @available_keywords = @scoping_rule.scopable.constantize.available_keywords
    end

    def update
      @role = Role.find(params[:role_id])
      @scoping_rule = ScopingRule.find(params[:id])
      if @scoping_rule.update(scoping_rule_update_params)
        flash[:success] = "Configured #{@scoping_rule.scopable}:#{@scoping_rule.keyword} for #{@role.name}"
        redirect_to role_path(@role)
      else
        flash.now[:error] = 'There was an issue updating this scoping rule'
        @available_keywords = @scoping_rule.scopable.constantize.available_keywords
        render 'edit'
      end

    end

    private

    def scoping_rule_params
      params.require(:scoping_rule)
            .permit(
              :scopable,
              :keyword
            )
    end

    def scoping_rule_update_params
      params.require(:scoping_rule)
            .permit(:keyword)
    end
  end
end

app/controllers/authz/stale_controller_actions_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class StaleControllerActionsController < ApplicationController
    def index
      @stale_controller_actions = ControllerAction.stale
    end
  end
end

app/controllers/authz/validations/action_names_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class Validations::ActionNamesController < ApplicationController
    def new
      _controller_name = params[:controller_name]
      _action_name = params[:controller_action][:action]
      found = ControllerAction.reachable_controller_actions[_controller_name].try(:include?, _action_name)

      respond_to do |format|
        format.json {render :json => found}
      end
    end
  end
end

app/controllers/authz/validations/business_process_names_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class Validations::BusinessProcessNamesController < ApplicationController
    def new
      name = params[:business_process][:name]
      # found = BusinessProcess.exists?(name: name)
      found = BusinessProcess.exists?(code: name.parameterize(separator: '_'))

      respond_to do |format|
        format.json {render :json => !found}
      end
    end

    def edit
      name = params[:business_process][:name]
      business_process = BusinessProcess.find_by(code: name.parameterize(separator: '_'))
      # found = BusinessProcess.exists?(name: name)

      found = business_process.present? && business_process.id != params[:id].to_i
      respond_to do |format|
        format.json {render :json => !found}
      end
    end

  end
end

app/views/authz/business_processes/_business_process.html.slim
tr.is-clickable[data-url="#{business_process_path(business_process)}"]
  td = business_process.id
  td = business_process.name
  td = business_process.code
  td = business_process.description

  - show_bp_path = business_process_path(business_process)
  - if authorized_path? show_bp_path, skip_scoping: true
    td = link_to show_bp_path do
      i.fa-chevron-right.fa

app/views/authz/business_processes/_empty_association.html.slim
.card
  .card-content
    .content
      p.title.is-4.has-text-centered No Business Processes associated yet
      p Business Processes are the parents of grouped actions needed to perform a task. For example: Ship Orders, Create invoice or Revert reimbursement.
    .has-text-centered
      = authz_link_to 'Add business process', parent_edit_link, {class: 'button is-primary'}, skip_scoping: true

app/views/authz/business_processes/_fields.html.slim
.field
  = f.label :name, class: 'label'
  .control
    = f.text_field :name, class: 'input', required: true, data: { validation_path: name_validation_path }
.field
  = f.label :description, class: 'label'
  .control
    = f.text_area :description, class: 'input', required: true
.field
  = f.label :role_ids, class: 'label'
  .control
    = f.select 'role_ids', options_for_select(::Authz::Role.all.pluck(:name, :id), f.object.role_ids), {}, { multiple: true }
.field
  = f.label :controller_action_ids, class: 'label'
  .control
    = f.select 'controller_action_ids', options_for_select(::Authz::ControllerAction.all.map{|ca| [ca.to_s, ca.id]}, f.object.controller_action_ids), {}, { multiple: true }

app/views/authz/business_processes/_help.html.slim
h2.title.is-4 Help
= render 'authz/shared/what_is_bp'
.content
  h3.title.is-6 How to choose a name?
  p.is-justified
    | Use something that makes sense for your business. Starting with a verb tends to work nicely&nbsp;
    | with role descriptions. For example: the "director" role is able to "launch marketing campaigns" and&nbsp;
    | "publish reports".
.content
  h3.title.is-6 What should the description contain?
  p.is-justified
    | The description field is to help you and your colleagues to remember what a the&nbsp;
    | business process is about at a glance.

app/views/authz/business_processes/_table.html.slim
#business_processes
  - if business_processes.blank?
    .has-text-centered
      p.title.is-4 No Business Processes yet
      p.subtitle.is-6 Create one here
      = authz_link_to 'New business process', new_business_process_path, {class: 'button is-primary'}, skip_scoping: true
  - else
    .card
      .card-content = paginate business_processes, views_prefix: 'authz', param_name: 'business_processes_page'
      table.table.is-fullwidth.is-striped.is-hoverable
        thead
          tr
            th ID
            th Name
            th Code name
            th Description
            th
        tbody
          = render business_processes

app/views/authz/business_processes/edit.html.erb
<h1>BusinessProcesses#edit</h1>
<p>Find me in app/views/authz/business_processes/edit.html.erb</p>

app/views/authz/business_processes/edit.html.slim
= content_for :nav_title do
  = "#{action_name.titleize} #{@business_process.name}"

section.section
  .container
    .columns
      .column.is-three-fifths
        .card
          = render 'layouts/authz/error_messages', object: @business_process
          .card-content
            = form_for @business_process do |f|
              = render 'fields', f: f, name_validation_path: edit_validations_business_process_name_path(@business_process)
              .field
                .control
                  = f.submit 'Save', class: 'button is-primary is-fullwidth'
      .column
        = render 'help'

app/views/authz/business_processes/index.html.slim
= render 'authz/shared/index_navbar_content'

section.section
  .container
    = render 'table', business_processes: @business_processes

app/views/authz/business_processes/new.html.erb
<h1>BusinessProcesses#new</h1>
<p>Find me in app/views/authz/business_processes/new.html.erb</p>

app/views/authz/business_processes/new.html.slim
= content_for :nav_title do
  = 'New Business Process'

section.section
  .container
    .columns
      .column.is-three-fifths
        .card
          = render 'layouts/authz/error_messages', object: @business_process
          .card-content
            = form_for @business_process do |f|
              = render 'fields', f: f, name_validation_path: new_validations_business_process_name_path
              .field
                .control
                  = f.submit 'Create', class: 'button is-primary is-fullwidth'
      .column
        = render 'help'

app/views/authz/business_processes/show.html.slim
= content_for :nav_title do
  = @business_process.name.titleize
= content_for :nav_links do
  .buttons
    = authz_link_to 'Edit', edit_business_process_path(@business_process), { class: 'button is-primary' }, skip_scoping:  true
    = authz_link_to 'Destroy',
                    business_process_path(@business_process),
                    { method: :delete,
                      class: 'button is-danger',
                      data: { confirm: '¿Are you sure? This action is undoable' } },
                    skip_scoping:  true

section.section
  .columns
    .column
      h2.title.is-4 Controller Actions
      - if @associated_controller_actions.blank?
        = render 'authz/controller_actions/empty_association', parent_edit_link: edit_business_process_path(@business_process)
      - else
        = render 'authz/controller_actions/table', controller_actions: @associated_controller_actions
    .column
      h2.title.is-4 Roles
      - if @associated_roles.blank?
        = render 'authz/roles/empty_association', parent_edit_link: edit_business_process_path(@business_process)
      - else
        = render 'authz/roles/table', roles: @associated_roles
  - Authz.rolables.each do |rolable|
    = render 'authz/rolables/table_from_association', rolable: rolable, parent_instance: @business_process