config/routes.rb
Authz::Engine.routes.draw do

  root 'home#index'
  resources :controller_actions
  resources :pending_controller_actions, only: [:index]
  resources :stale_controller_actions, only: [:index]
  resources :business_processes
  resources :roles do
    resources :scoping_rules, only: [:new, :create, :edit, :update]
  end

  namespace :bulk do
    post 'controller_actions/create'
    delete 'controller_actions/destroy'
  end

  namespace :validations do
    resources :controller_names, only: [:new]
    resources :action_names, only: [:new]
    resources :business_process_names, only: [:new, :edit]
    resources :role_names, only: [:new, :edit]
  end

  Authz.rolables.each do |rolable|
    resources rolable.authorizable_association_name, only: [:index, :show, :edit, :update], controller: :rolables
  end

end

app/models/authz/controller_action.rb
module Authz
  # Represents a single reachable controller
  # action from the host application's router, including all library
  # internal routes.
  class ControllerAction < self::ApplicationRecord

    # Validations
    # ==========================================================================
    validates :controller, presence: true
    validates :action, presence: true
    validates_uniqueness_of :controller, scope: %i[action]
    validate :controller_action_pair_exist

    # Associations
    # ==========================================================================
    has_many :business_process_has_controller_actions,
             class_name: 'Authz::BusinessProcessHasControllerAction',
             foreign_key: 'authz_controller_action_id',
             inverse_of: :controller_action,
             dependent: :destroy
    has_many :business_processes,
             through: :business_process_has_controller_actions,
             dependent: :destroy
    has_many :roles, through: :business_processes
    has_many :role_grants, through: :roles

    accepts_nested_attributes_for :business_processes

    # Callbacks
    # ==========================================================================
    after_update :touch_upstream_instances

    # Class Methods
    # ==========================================================================

    # @return [Hash] reachable controller actions declared in the host app's router
    def self.main_app_reachable_controller_actions
      extract_reachable_controller_actions(Rails.application)
    end

    # @return [Hash] reachable controller actions declared in the Engine's router
    def self.engine_reachable_controller_actions
      extract_reachable_controller_actions(Authz::Engine)
    end

    # Combines the reachable controller actions from the engine and the main app
    # giving precedence to the main app in case of overwrite
    # @return [Hash] reachable controller actions
    # @see .main_app_reachable_controller_actions
    # @see .engine_reachable_controller_actions
    def self.reachable_controller_actions
      app_cas = main_app_reachable_controller_actions
      engine_cas =  engine_reachable_controller_actions
      repeated_keys = app_cas.keys & engine_cas.keys
      res = engine_cas.merge(app_cas)
      repeated_keys.each { |rk| res[rk] = app_cas[rk] | engine_cas[rk] }
      res
    end

    # @return [Array<Authz::ControllerAction>]
    #         controller action instances reachable from the router but not present in the database
    # @api private
    # @see .reachable_controller_actions
    def self.pending
      router_ca_pairs = []
      reachable_controller_actions.each do |c_name, action_arr|
        action_arr.each do |a_name|
          router_ca_pairs << [c_name, a_name]
        end
      end

      dp_ca_pairs = all.pluck(:controller, :action)

      pending = router_ca_pairs - dp_ca_pairs
      pending.map{ |ca_pair| new(controller: ca_pair.first, action: ca_pair.last) }
    end

    # @return [Array<Authz::ControllerAction>] controller actions that are created in the database that
    #         are no longer reachable from the router
    # @api private
    # @see .reachable_controller_actions
    def self.stale
      # TODO: Refactor and test
      stale = []
      find_each do |ca|
        is_included = reachable_controller_actions[ca.controller].try(:include?, ca.action)
        stale << ca unless is_included
      end
      stale
    end

    # Creates all pending controller actions in the database.
    # The creation either succeeds or fails completely
    # @return [Array<Authz::ControllerAction>] all controller action instances
    #         that have been created.
    # @api private
    # @see .pending
    def self.create_all_pending!
      transaction do
        pending.each do |pca|
          pca.save!
        end
      end
    end

    # Instance Methods
    # ==========================================================================

    # @return [String] concatenation of controller#action-id
    def to_s
      "#{controller}##{action}-#{id}"
    end

    # @return [String] description of a controller action, parsed through the
    #                  controller_metadata_service
    def description
      Authz.metadata_service.get_controller_action_description(self.controller, self.action)
    end

    private

    # Introspects the given application's or engine's routes and returns a list
    # of hashes of all reachable controller actions with the format
    # { "orders" =>["new", "edit", "update"],
    #   "authz/business_processes" => ["index", ...]  }
    # @param app: An instance of a rails application or Engine
    #             e.g. Rails.application or Authz::Engine
    def self.extract_reachable_controller_actions(app)
      result = {}
      routes = app.routes.set.anchored_routes.map(&:defaults).uniq
      routes.each do |route|
        controller = route[:controller]
        action = route[:action]
        if result.has_key? controller
          result[controller].push(action)
        else
          result[controller] = [action]
        end
      end
      result
    end

    def controller_action_pair_exist
      unless self.class.reachable_controller_actions[controller].try(:include?, action)
        errors.add(:base, 'the controller action you are trying to save is not included in the routes')
      end
    end

    def touch_upstream_instances
      time = Time.now
      business_process_has_controller_actions.update_all(updated_at: time)
      business_processes.update_all(updated_at: time)
      roles.update_all(updated_at: time)
    end

  end
end

app/controllers/authz/application_controller.rb
module Authz
  # Inherits from the host app's ApplicationController so that all of it's methods
  # are available for the engine.
  #
  # All engine's controllers inherit from this class.
  # @api private
  class ApplicationController < ::ApplicationController
    include Authz::Controllers::AuthorizationManager

    protect_from_forgery with: :exception
    before_action :authenticate_authz_user
    before_action { authorize skip_scoping: true }
    around_action :verify_authorized

    private
    # Calls the authentication method configured by the main application
    def authenticate_authz_user
      send(Authz.force_authentication_method)
    end

  end
end

app/controllers/authz/bulk/controller_actions_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class Bulk::ControllerActionsController < ApplicationController

    def create
      pending_actions = Authz::ControllerAction.create_all_pending!
      flash[:success] = "#{pending_actions.size} actions successfully created!"
      redirect_to root_path
    end

    def destroy
      ActiveRecord::Base.transaction do
        @stale_actions = ::Authz::ControllerAction.stale
        @stale_actions.each do |controller_action_hash|
          ::Authz::ControllerAction.find_by(
            controller: controller_action_hash[:controller],
            action: controller_action_hash[:action],
          ).destroy!
        end
      end
      flash[:success] = "#{@stale_actions.count} actions successfully destroyed!"
      redirect_to root_path
    end

  end
end

app/controllers/authz/business_processes_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class BusinessProcessesController < ApplicationController

    def index
      @business_processes = BusinessProcess.all.order(created_at: :desc).page(params[:business_processes_page])
    end

    def show
      @business_process = BusinessProcess.find(params[:id])
      @associated_controller_actions = @business_process.controller_actions.distinct.page(params[:controller_actions_page]).per(10)
      @associated_roles = @business_process.roles.distinct.page(params[:roles_page]).per(10)
    end

    def new
      @business_process = BusinessProcess.new
    end

    def create
      @business_process = BusinessProcess.new(business_process_params)
      if @business_process.save
        redirect_to business_process_path(@business_process)
        flash[:success] = "#{@business_process.name} created successfully"
      else
        flash.now[:error] = "There was an issue creating this business process"
        render 'new'
      end
    end

    def edit
      @business_process = BusinessProcess.find(params[:id])
    end

    def update
      @business_process = BusinessProcess.find(params[:id])
      if @business_process.update(business_process_params)
        flash[:success] = "#{@business_process.name} updated successfully"
        redirect_to business_process_path(@business_process)
      else
        flash.now[:error] = "There was an issue updating this business process"
        render 'edit'
      end
    end

    def destroy
      @business_process = BusinessProcess.find(params[:id])
      if @business_process.destroy
        flash[:success] = "#{@business_process.name} destroyed successfully"
        redirect_to business_processes_path
      else
        flash.now[:error] = "There was an issue destroying #{@business_process.name}"
        render 'show'
      end
    end

    private

    def business_process_params
      params.require(:business_process)
            .permit(
              :name,
              :description,
              controller_action_ids: [],
              role_ids: []
            )
    end
  end
end

app/controllers/authz/controller_actions_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class ControllerActionsController < ApplicationController
    def index
      @controller_actions = ControllerAction.all.order(created_at: :desc).page(params[:controller_actions_page])
    end

    def show
      @controller_action = ControllerAction.find(params[:id])
      @associated_business_processes = @controller_action.business_processes.distinct.page(params[:business_processes_page]).per(10)
      @associated_roles = @controller_action.roles.distinct.page(params[:roles_page]).per(10)
    end

    def new
      @controller_action = ControllerAction.new
    end

    def create
      @controller_action = ControllerAction.new(controller_action_create_params)
      if @controller_action.save
        flash[:success] = "#{@controller_action.to_s} created successfully"
        redirect_to controller_action_path(@controller_action)
      else
        flash.now[:error] = "There was an issue creating this controller action"
        render 'new'
      end
    end

    def edit
      @controller_action = ControllerAction.find(params[:id])
    end

    def update
      @controller_action = ControllerAction.find(params[:id])
      if @controller_action.update(controller_action_update_params)
        flash[:success] = "#{@controller_action.to_s} updated successfully"
        redirect_to controller_action_path(@controller_action)
      else
        flash.now[:error] = "There was an issue updating #{@controller_action.to_s}"
        render 'edit'
      end
    end

    def destroy
      @controller_action = ControllerAction.find(params[:id])
      if @controller_action.destroy
        flash[:success] = "#{@controller_action.to_s} destroyed successfully"
        redirect_to controller_actions_path
      else
        flash.now[:error] = "There was an issue destroying #{@controller_action.to_s}"
        render 'show'
      end
    end

    private

    def controller_action_create_params
      params.require(:controller_action)
            .permit(
              :controller,
              :action,
              business_process_ids: []
            )
    end

    def controller_action_update_params
      params.require(:controller_action)
            .permit(
              :controller,
              :action,
              business_process_ids: []
            )
    end
  end
end

app/controllers/authz/home_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class HomeController < ApplicationController
    def index
      @pending_controller_actions = ControllerAction.pending
      @stale_controller_actions = ControllerAction.stale
      @invalid_scoping_rules = ScopingRule.where.not(scopable: Authz::Scopables::Base.get_scopables_names).pluck(:scopable).uniq
    end
  end
end

app/controllers/authz/pending_controller_actions_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class PendingControllerActionsController < ApplicationController
    def index
      @pending_controller_actions = ControllerAction.pending
                                                    .sort_by { |ca| ca[:controller] }
    end
  end
end

app/controllers/authz/rolables_controller.rb
require_dependency "authz/application_controller"

module Authz
  # Handles the controller actions related to the rolables
  # @api private
  class RolablesController < ApplicationController

    def index
      @rolables = rolable.all.page(params[:page])
    end

    def show
      @rolable = rolable.find(params[:id])
      @associated_roles = @rolable.roles.page(1)
      @associated_business_processes = @rolable.business_processes.page(params[:business_processes_page])
      @associated_controller_actions = @rolable.controller_actions.page(params[:controller_actions_page])
    end

    def edit
      @rolable = rolable.find(params[:id])
    end

    def update
      @rolable = rolable.find(params[:id])
      if @rolable.update(rolable_params)
        flash[:success] = "#{@rolable.authz_label} updated successfully"
        redirect_to send("#{@rolable.model_name.singular}_path", @rolable)
      else
        flash.now[:error] = "There was an issue updating #{@rolable.authz_label}"
        render 'edit'
      end
    end

    private

    def rolable
      ::Authz.rolables.each do |klass|
        klass_name = klass.authorizable_association_name
        regex = /\A\/#{klass_name}(\/|\z)/
        next unless regex.match request.path_info
        return klass
      end
    end

    def rolable_params
      params.require(rolable.model_name.singular)
        .permit(role_ids: [])
    end


  end
end

app/controllers/authz/roles_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class RolesController < ApplicationController

    def index
      @roles = Role.all.page(params[:roles_page])
    end

    def show
      @role = Role.find(params[:id])
      @associated_controller_actions = @role.controller_actions.distinct.page(params[:controller_actions_page]).per(10)
      @associated_business_processes = @role.business_processes.distinct.page(params[:business_processes_page]).per(10)
      @scoping_rules = {}
      ::Authz::Scopables::Base.get_scopables_modules.each do |scoping_module|
        @scoping_rules[scoping_module.to_s] = ScopingRule.find_by(scopable: scoping_module.to_s,
                                                                  role: @role)
      end
    end

    def new
      @role = Role.new
    end

    def create
      @role = Role.new(role_params)
      if @role.save
        flash[:success] = "#{@role.name} created successfully"
        redirect_to role_path(@role)
      else
        flash.now[:error] = "There was an issue creating this role"
        render 'new'
      end
    end

    def edit
      @role = Role.find(params[:id])
    end

    def update
      @role = Role.find(params[:id])
      if @role.update(role_params)
        flash[:success] = "#{@role.name} updated successfully"
        redirect_to role_path(@role)
      else
        flash.now[:error] = "There was an issue updating this role"
        render 'edit'
      end
    end

    def destroy
      @role = Role.find(params[:id])
      if @role.destroy
        flash[:success] = "#{@role.name} destroyed successfully"
        redirect_to roles_path
      else
        flash.now[:error] = "There was an issue destroying #{@role.name}"
        render 'show'
      end
    end

    private

    def role_params
      permitted_arguments = [:name, :description, business_process_ids: []]
      ::Authz.rolables.each do |rolable|
        permitted_arguments << { "#{rolable.model_name.singular}_ids"=> [] }
      end
      params.require(:role)
            .permit(permitted_arguments)
    end
  end
end

app/controllers/authz/stale_controller_actions_controller.rb
require_dependency "authz/application_controller"

module Authz
  # @api private
  class StaleControllerActionsController < ApplicationController
    def index
      @stale_controller_actions = ControllerAction.stale
    end
  end
end

app/views/authz/roles/_empty_association.html.slim
.card
  .card-content
    .content
      p.title.is-4.has-text-centered No Roles associated yet
      p Roles are the main grouping for your users in your software. For example: Office manager, General Director or Business Analyst.
    .content.has-text-centered
      = authz_link_to 'Add role', parent_edit_link, {class: 'button is-primary'}, skip_scoping: true

app/views/authz/roles/_fields.html.slim
.field
  = f.label :name, class: 'label'
  .control
    = f.text_field :name, class: 'input', required: true, data: { validation_path: name_validation_path }
.field
  = f.label :description, class: 'label'
  .control
    = f.text_area :description, class: 'input', required: true

.field
  = f.label :business_process_ids, class: 'label'
  .control
    = f.select 'business_process_ids', options_for_select(::Authz::BusinessProcess.all.pluck(:name, :id), f.object.business_process_ids), {}, { multiple: true, class: 'j-multiselectable' }

- ::Authz.rolables.each do |rolable|
  .field
    = f.label "#{rolable.model_name.singular}_ids", class: 'label'
    .control
      = f.select "#{rolable.model_name.singular}_ids", options_for_select(rolable.all.map{ |r| [r.authz_label, r.id] }, f.object.role_grants.where(rolable_type: rolable.to_s).pluck(:rolable_id)), {}, { multiple: true, class:'j-multiselectable' }

app/views/authz/roles/_help.html.slim
h2.title.is-4 Help
.content
  h3.title.is-6 What is a Role?
  p.is-justified
    | Roles are granted the power to execute one or many Business Processes subject to the scoping rules you define.
    | Roles typically are business specific.

.content
  h3.title.is-6 What should the description contain?
  p.is-justified
    | The description field is to help you and your colleagues to remember what a the&nbsp;
    | role can do at a glance.

app/views/authz/roles/_role.html.slim
tr.is-clickable[data-url="#{role_path(role)}"]
  td = role.id
  td = role.name
  td = role.code
  td = role.description

  - show_r_path = role_path(role)
  - if authorized_path? show_r_path, skip_scoping: true
    td = link_to show_r_path do
      i.fa-chevron-right.fa

app/views/authz/roles/_table.html.slim
.card
  .card-content = paginate roles, views_prefix: 'authz', param_name: 'roles_page'
  table.table.is-fullwidth.is-striped.is-hoverable
    thead
      tr
        th ID
        th Name
        th Code name
        th Description
        th
    tbody
      = render roles

app/views/authz/roles/edit.html.erb
<h1>Roles#edit</h1>
<p>Find me in app/views/authz/roles/edit.html.erb</p>

app/views/authz/roles/edit.html.slim
= content_for :nav_title do
  = "#{action_name.titleize} #{@role.name}"

section.section
  .container
    .columns
      .column.is-three-fifths
        .card
          = render 'layouts/authz/error_messages', object: @role
          .card-content
            = form_for @role do |f|
              = render 'fields', f: f, name_validation_path: edit_validations_role_name_path(@role)
              .field
                .control
                  = f.submit 'Save', class: 'button is-primary is-fullwidth'
      .column
        = render 'help'

app/views/authz/roles/index.html.slim
= render 'authz/shared/index_navbar_content'

section.section
  .container
    = render 'table', roles: @roles

app/views/authz/roles/new.html.erb
<h1>Roles#new</h1>
<p>Find me in app/views/authz/roles/new.html.erb</p>

app/views/authz/roles/new.html.slim
= content_for :nav_title do
  = 'New Role'

section.section
  .container
    .columns
      .column.is-three-fifths
        .card
          = render 'layouts/authz/error_messages', object: @role
          .card-content
            = form_for @role do |f|
              = render 'fields', f: f, name_validation_path: new_validations_role_name_path
              .field
                .control
                  = f.submit 'Create', class: 'button is-primary is-fullwidth'
      .column
        = render 'help'

app/views/authz/roles/show.html.slim
= content_for :nav_title do
  = @role.name.titleize
= content_for :nav_links do
  .buttons
    = authz_link_to 'Edit', edit_role_path(@role), {class: 'button is-primary'}, skip_scoping: true
    = authz_link_to 'Destroy', role_path(@role),
                    {method: :delete, class: 'button is-danger', data: { confirm: '¿Are you sure? This action is undoable' }},
                    skip_scoping: true

section.section
  .columns
    .column
      h2.title.is-4 Business Processes
      - if @associated_business_processes.blank?
        = render 'authz/business_processes/empty_association', parent_edit_link: edit_controller_action_path(@role)
      - else
        = render 'authz/business_processes/table', business_processes: @associated_business_processes
    .column
      h2.title.is-4 Controller Actions
      - if @associated_controller_actions.blank?
        = render 'authz/controller_actions/empty_association', parent_edit_link: edit_controller_action_path(@role)
      - else
        = render 'authz/controller_actions/table', controller_actions: @associated_controller_actions
section.section
  h2.title.is-4 Scoping Rules
  .card
    table.table.is-fullwidth
      thead
        tr
          th Name
          th Value
          th
      tbody
        - @scoping_rules.each do |rule_name, instance|
          tr
            td = rule_name
            td = instance.try(:keyword) || 'Not created yet'
            td
              - if instance
                = authz_link_to 'Edit', edit_role_scoping_rule_path(@role, instance), {class: 'button is-primary'}, skip_scoping: true
              - else
                = authz_link_to 'New', new_role_scoping_rule_path(@role, scopable: rule_name), {class: 'button is-primary'}, skip_scoping: true
section.section
  - Authz.rolables.each do |rolable|
    = render 'authz/rolables/table_from_association', rolable: rolable, parent_instance: @role